name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
        - name: print
          run: |
            echo "${{ secrets.TAILSCALE_AUTHKEY }}"
        - name: Tailscale
          uses: tailscale/github-action@v1
          with:
            authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
            version: 1.36.2 