name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
        - name: print
          env:
            TAIL_VAR_1: ${{ secrets.TAILSCALE_AUTHKEY }}
          run: |
            echo "$TAIL_VAR_1"
        - name: Tailscale
          env:
            TAIL_VAR_1: ${{ secrets.TAILSCALE_AUTHKEY }}
          uses: tailscale/github-action@v1
          with:
            authkey: $TAIL_VAR_1
            version: 1.36.2 