name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
        - name: print
          run: |
            echo "${{ env.TAIL_VAR }}"
        - name: Tailscale
          uses: tailscale/github-action@v1
          with:
            authkey: ${{ env.TAIL_VAR }}
            version: 1.36.2 